services:
  # Frontend service
  frontend_centralized:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV_MODE}
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    networks:
      - centralized_network
    depends_on:
      - backend_centralized

  # Backend service
  backend_centralized:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV_MODE}
    volumes:
      - ./Backend:/backend
    ports:
      - "8000:8000"
    networks:
      - centralized_network
      - shared_net
    depends_on:
      - db_centralized

  # PostgreSQL database service
  db_centralized:
    image: postgres:17
    env_file:
      - .env.${ENV_MODE}
    networks:
      - centralized_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Nginx service
  nginx_centralized:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend_centralized
      - backend_centralized

volumes:
  pgdata:

networks:
  centralized_network:
    driver: bridge
  shared_net:
    external: true