services:
  # Frontend service
  frontend_ilp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV_MODE}
    ports:
      - "3001:4000"
    depends_on:
      - backend_ilp

  # Backend service
  backend_ilp:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV_MODE}
    volumes:
      - ./Backend:/backend
    ports:
      - "8001:6000"
    networks:
      - ilp_network
      - shared_net
    depends_on:
      - db_ilp

  # PostgreSQL database service
  db_ilp:
    image: postgres:17
    env_file:
      - .env.${ENV_MODE}
    networks:
      - ilp_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Nginx service
  nginx_ilp:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8024:80"
    depends_on:
      - frontend_ilp
      - backend_ilp

volumes:
  pgdata:

networks:
  ilp_network:
    driver: bridge
  shared_net:
    external: true