name: CI/CD - Deploy Centralized & Subsidiary Backends to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push-centralized:
    name: Build & Push Centralized Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Centralized Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./Centralized
          file: ./Centralized/Dockerfile
          push: true
          tags: aryanbadkul/centralized-backend:latest

  build-and-push-ilp:
    name: Build & Push ILP Backend
    runs-on: ubuntu-latest
    needs: build-and-push-centralized

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Subsidiary Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./MyBeastSummerILP-main
          file: ./MyBeastSummerILP-main/Dockerfile
          push: true
          tags: aryanbadkul/ilp-backend:latest
